### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by mogusbi** [mogusbi/gulp-starter#6]
# TODOs for version 2

- [ ] Create a Yeoman generator to create a project

- [x] Rewrite tasks in ES6

- [x] Use project based Webpack configurations

- [x] Allow all configurations to be configurable

- [x] Plug-in custom tasks

- [x] Remove project type references (i.e. Angular 1 or 2)

- [ ] TS/ESlint should look by default in the project and then load in built in rules if they don't exist

- [x] Try to use Webpack instead of webpack-stream 

- [x] Look into replacing BrowserSync with Express server 

- [x] Look into moving moving things like the rev-manifest into a tmp folder that's deleted after build 

- [x] Generate size report

- [ ] Publish an actual npm package `@mogusbi/gulp-starter`

## Yeoman questions
1. Project name
2. Scripting (ts/js)
3. Enable HTML minification (true/false)
4. Enable uncss (false/true)
5. Karma (true/false)
6. Protractor (true/false)
7. Node version (6)

## Task list
1. Clear (rename to Clean)
2. Copy and process static assets
3. Generate templates
4. Linting
5. Compile SCSS
6. Generate revisions for static assets
7. Update references in CSS and favicon manifests to use rev'd static asset paths
8. Generate revisions for CSS and favicon manifests
9. Compile scripts
10. Update references for everything in html templates

**Comment by mogusbi** [comment]
Bugs that need fixing

- [ ] Fail favicon task silently if icon doesn't exist

- [x] SCSS causing task to crash

- [ ] Stop it failing if webpack config doesn't exist

- [x] Favicon manifest revisioning
